---
# Groups representando times do Azure AD.
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineering
  title: Platform Engineering
spec:
  type: team
  profile:
    displayName: Platform Engineering
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backend-engineers
  title: Backend Engineers
spec:
  type: team
  profile:
    displayName: Backend Engineers
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  title: Engineering
spec:
  type: department
  profile:
    displayName: Engineering
  children:
    - platform-engineering
    - backend-engineers
